// <auto-generated />
using KompleksinisV2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace KompleksinisV2.Migrations
{
    [DbContext(typeof(Data.AppDbContext))]
    [Migration("20171209133125_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KompleksinisV2.Models.Course", b =>
                {
                    b.Property<int>("CourseID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Title");

                    b.HasKey("CourseID");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("KompleksinisV2.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("Email");

                    b.Property<string>("MobileNumber");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<int>("PositionID");

                    b.Property<int>("SectorID");

                    b.Property<string>("Surname");

                    b.HasKey("ID");

                    b.HasIndex("PositionID");

                    b.HasIndex("SectorID");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("KompleksinisV2.Models.Mark", b =>
                {
                    b.Property<int>("MarkID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CourseID");

                    b.Property<int>("EmployeeID");

                    b.Property<int>("Grade");

                    b.HasKey("MarkID");

                    b.HasIndex("CourseID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("Mark");
                });

            modelBuilder.Entity("KompleksinisV2.Models.Message", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("EmployeeID");

                    b.Property<DateTime>("WriteDate");

                    b.Property<string>("WrittenText");

                    b.HasKey("ID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("KompleksinisV2.Models.Position", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("KompleksinisV2.Models.Sector", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Sector");
                });

            modelBuilder.Entity("KompleksinisV2.Models.Employee", b =>
                {
                    b.HasOne("KompleksinisV2.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KompleksinisV2.Models.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KompleksinisV2.Models.Mark", b =>
                {
                    b.HasOne("KompleksinisV2.Models.Course", "Course")
                        .WithMany("Mark")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KompleksinisV2.Models.Employee", "Employee")
                        .WithMany("Marks")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KompleksinisV2.Models.Message", b =>
                {
                    b.HasOne("KompleksinisV2.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeID");
                });
#pragma warning restore 612, 618
        }
    }
}
